[package]
name = "VAL-IOT"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.12.0"
futures-util = "0.3.29"
reqwest = {version = "0.11.22", features = ["json", "stream"]}
serde = "1.0.189"
serde_json = "1.0.108"
#rppal = "0.15.0"
tokio = {version = "1.33.0", features = ["full"]}
